import 'package:flutter/material.dart';

class ApiConstants {
  static const String baseUrl = 'http://devoteematrimony.aks.5g.in/api/';
  static const String loginUrl = 'login';
  static const String ragisUrl = "registration";
  static const String countryUrl = "country-list";
  static const String stateurl = "state-list";
  static const String cityUrl = "city-list";
  static const String countryCodeUrl = "country-code";
  static const String religionUrl = "get-religion";
  static const String castUrl = "cast-list";
  static const String subCastUrl = "sub-cast-list";
  static const String userUrl = "user";
  static const String dietUrl = "diet-list";
  static const String professionUrl = "title-of-profession";
  static const String maritalUrl = "marital-status-list";
  static const String highestQualUrl = "highest-qualification-list";
  static const String professionalQualUrl = "get-professional-qualification";
  static const String incomeUrl = "income-list";
  static const String mothertongueUrl = "mother_tongue_list";
  static const String heightUrl = "get-height";
  static const String weightUrl = "get-weight";
  static const String relationUrl = "get-relationship";
  static const String residencetypeUrl = "residence-type-list";
  static const String permanenttypeUrl = "permanent-house-type";
  static const String employmentUrl = "employment";
  static const String drinkhabitsUrl = "drinking-habits-list";
  static const String smokehabitsUrl = "smoking-habits-list";
  static const String partnerpreferenceUrl = "update-partner-preference";
  static const String educationlistUrl = "get-education";
  static const String searchUrl = "member/search";
  static const String proileDetailsUrl = "member/view-profile";
  static const String sentInvitationUrl = "member/sent-invitation";
  static const String inboxSentUrl = "member/invitation-sent-list";
  static const String inboxReceivedUrl = "member/received-invitation-request";
  static const String declinedUrl = "member/declined-invitation";
  static const String acceptedUrl = "member/accept-invitation";
  static const String feedbackUrl = "member/save-feedback";
  static const String complaintUrl = "member/save-complaint";
  static const String dashboardUrl = "member/dashboard";
  static const String testimonialUrl = "member/testimonial-list";
  static const String suggestionUrl = "member/save-suggestion";
  static const String collaborateUrl = "member/save-collaborate";
  static const String matchesUrl = "member/matches";
  static const String shortlistUrl = "member/shortlist";
  static const String shortlistedUrl = "member/short-listed-profile-list";
  static const String withdrawalUrl = "member/withdrawal-request";
  static const String couponsUrl = "member/coupon-list";
  static const String packageUrl = "member/package-list";
  static const String buyPackageUrl = "member/checkout";
  static const String langaugeUrl = "get-languages";
  static const String accountSettingUrl = "member/user-setting";
  static const String deletePhotoUrl = "member/delete-photo";
  static const String recommendedUrl = "member/inspiration-list";
  static const String musicUrl = "member/songs-list";
  static const String htmlContentUrl = "member/pages";
  static const String blockUrl = "member/block-user";
  static const String blockProfileUrl = "member/block-user-list";
  static const String addTestimonialUrl = "member/save-testimonial";
  static const String applyCouponUrl = "member/apply-coupon";
}

late Size mq;
